version: '3.1'
services:
  web:
    image: php:8.1-apache
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/

  mysql:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sekret
